### ISSUE TITLE
Адаптировать форму “Приём” для принятия данных плана лечения.

### ISSUE THREAD

**Issue by YerzhanUtelbayev** [Attractor-JS2/ESDP#11]
**Конечный результат**
Данные плана лечения передаются в форму приёма пациента.
В поле выбора выполняемой процедуры есть возможность выбрать пункт из плана лечения.
Есть возможность выполнить процедуру, отсутствовавшую в плане лечения.
Данные плана лечения дополняются если выполнена новая процедура.
Выполненные процедуры с датой выполнения и план лечения сохраняются для возможности построения на их основе диаграммы.

**План решения**
Настроить временные роуты для переключения между формами.
Реализовать передачу данных между контейнерами.
Реализовать возможность выбора процедур из плана лечения.
Реализовать сохранение выполненной процедуры с текущей датой.

**Мотивация**
Возможность позволит сократить время требуемое для протоколирования выполненных процедур.

**Критерии приёмки**
Данные для полей выбора попадают из плана лечения.
Либо можно выбрать и добавить новую процедуру.

Планируемое время работы.
1 день.

**Comment by sv64ds** [comment]
Примерное время работы: 1 полный день для доведения до полность функционирующего базового состояния(тз + дополнительные материалы).
Изучил ТЗ подробнее, уточнил недопонимания с аналитиком и капитаном команды.

Задача на конец сегодняшнего дня:

- Создать роуты для формы приема и плана лечения
- Изучить работу селекционных меню в Formik
- Изменить существующие селекционные меню для выбора процедур на основе прототипа, составленного капитаном команды
- Создать обработчики изменений этих селекционных меню
- При наличии времени и сил, сделать дополнительные задачи

**Comment by sv64ds** [comment]
Из разговора с капитаном команды понял, что они не пришли к взаимопониманию с заказчиком, поэтому нами было принято решение не концентрировать внимание на передачу данных между формами и составление графика.

Я решил работать с передачей данных следующим образом: 
Я создал файл с Объектами типа JSON, всего у меня получилось 2 объекта:

1. Все возможные процедуры этапов, которые в теории может провести врач
2. Все процедуры с этапами, которые были установлены в плане лечения

Тем самым я имитировал поступающие данные в форму,
После чего на основе этих объектов я начал работать в форме.

**Comment by sv64ds** [comment]
План на сегодня:
Сохранять данные формы в localStorage
Добавить возможность добавлять процедуры, которые не прописаны в изначальном плане лечения
Сохранить новые процедуры в отдельный массив, данные из которого в дальнейшем добавятся в нужные блоки в плане лечения

По мере выполнения текущих задач буду добавлять новые
Примерное время на выполнение: беру с запасом весь оставшийся день для доведения до идеального состояния

**Comment by sv64ds** [comment]
Попытался реализовать подгрузку значений по умолчанию в селекционные меню, столкнулся с проблемой того, что я не могу установить значение по умолчанию при динамической подгрузке <option>'ов в select

**Comment by sv64ds** [comment]
Нашел отличное решение для связи стейта формы с localStorage:
Мне на помощь пришла библиотека от создателя Формика Джареда Палмера под названием  [formik-persist](https://github.com/jaredpalmer/formik-persist)

**Comment by sv64ds** [comment]
Довольно поздно сажусь за работу, в планах сегодня:
Исправить трудности с очисткой формы и отправить pull-request
Ознакомиться с форматом выходящих данных из плана лечения и связать обе формы
При возможности подключить библиотеку для построения диаграммы Ганта

**Comment by sv64ds** [comment]
Задерживаюсь в связи с несовпадением выходящих данных из одной формы, чтобы строить селекционные меню, с моими ожиданиями.
В кратчайшие сроки обработаю данные и запишу их в селекционные меню
