### ISSUE TITLE
Создать форму протокола первичного осмотра

### ISSUE THREAD

**Issue by sv64ds** [Attractor-JS2/ESDP#2]
[Первичный прием 1.docx](https://github.com/Attractor-JS2/ESDP/files/4332677/1.docx)
[Первичный прием 2.docx](https://github.com/Attractor-JS2/ESDP/files/4332678/2.docx)
**Конечный результат**

Создать форму протокола первичного осмотра пациента на основе приложенного файла.
Она будет содержать: 

- Анкетные данные пациента
- Факторы риска пациента (красные флаги)
- Данные об образе жизни пациента
- Текущее состояние здоровья пациента

**План решения**

1. Создать файл с названием **PrimaryAssesment.js** в папке с одноименным названием
2. Создать таблицу, содержащую анкетные данные пациента _(данные прописать вручную)_
3. Создать форму, содержащую:

- Основную информацию о пациенте(образ жизни, жалобы пациента, анализ заболевания и данные обследований)
- Список  так называемых 'красных флагов' - факторов риска пациента
- Список обследуемых зон с информацией  о текущем состоянии зоны в статике / динамике, полем примечания **(использовать приложенный файл в качестве шаблона)**
- Вывод врача, содержащий предварительный диагноз и рекомендациями по профилактике

**Мотивация** 

На основе данных, полученных из данного протокола составляется полный курс лечения пациента

**Критерии приемки**

В форме присутствуют все вышеперечисленные поля, которые сохраняются в локальный state и имеют 2-way-binding
Присутствует метод на отправку данных из формы, который выводит сформированные данные в консоль

**Планируемое время работы**
6 часов

**Comment by YerzhanUtelbayev** [comment]
Требуется уточнение у заказчика

**Comment by YerzhanUtelbayev** [comment]
Форма должна содержать
Анкетные данные пациента
Красные флаги (в виде чеклиста)
I Жалобы.
II Anamnesis vitae (анамнез жизни)
III Anamnesis morbi (анамнез заболевания)
IV Status praesens (состояние на момент осмотра)
V Status localis (локальный статус)
VI Дополнительные обследования
VII Диагноз
![image](https://user-images.githubusercontent.com/50818360/81073028-dab49700-8f08-11ea-8ff0-863740ef6e24.png)

**Comment by YerzhanUtelbayev** [comment]
Для эпикриза (этапного или исходного) и профилактики я думаю понадобится отдельная форма.
При успешном сохранении можно добавить переход на форму создания плана лечения. В сравнении с исходными документами форма не меняется.

**Comment by YerzhanUtelbayev** [comment]
Поля ввода формы:
Красные флаги (в виде чеклиста)
Жалобы пациента
Анамнез профессии и условия среды жизнедеятельности
Анамнез заболевания
Status praesens (состояние на момент осмотра)
Status localis (локальный статус)
Дополнительные обследования
Диагноз
```
{
redFlags: [ String ],
complaints: String,
anamnesisVitae: String,
anamnesisMorbi: String,
statusPraesens: String,
statusLocalis: String,
examinations: String,
diagnosis: String,
}
```
