### ISSUE TITLE
Форма логина

### ISSUE THREAD

**Issue by yelkanat** [Attractor-JS2/ESDP#44]
**Конечный результат:**
	Форма логина. При успешном логине происходит перенаправление на компонент Форма планирования курса лечения.
**План решения:**
	Создать форму с обязательными полями логина и пароля.
	Создать reducer и action для POST-запроса логина пользователя.
	Создать роут на POST запрос. Добавить контроллер на бэкенде, который будет возвращать статус 201 при наличии данных логина и пароля в request.
**Мотивация:**
	Компонент позволит оценить и спланировать дизайн переходов между вспомогательными компонентами фронте-енда.
**Критерии приёмки:**
	После ввода логина и пароля и нажатия на кнопку подтверждения, отправляется запрос на API. После успешного ответа происходит переход на компонент Форма планирования курса лечения.
**Планируемое время работы:**
	3 часа.

**Comment by YerzhanUtelbayev** [comment]
В будущем переход будет происходить на компонент выбора пациента. На эту форму будут перенаправляться только неаутентифицированные пользователи.
