### ISSUE TITLE
Форма планирования курса - адаптировать под изменный формат данных

### ISSUE THREAD

**Issue by YerzhanUtelbayev** [Attractor-JS2/ESDP#45]
**Конечный результат:**
Добавлены поля с планируемым количеством для каждой процедуры. Поля селект изменены на инпуты.
**План решения:**
Изменить селект элемент поля выбора области на инпут.
Изменить селект элемент поля выбора процедуры на инпут.
Добавить поле ввода количества процедур.
Дополнительно: продумать автозаполнение полей ввода, по 5-10 процедур в предлагаемых вариантах, поиск сочетания символов происходил по всей строке источника.
**Мотивация:**
Дополнит план курса лечения данными. Улучшит UX.
**Критерии приёмки:**
У каждой процедуры имеется возможность указать количество планируемых повторений.
Поля изменены на инпуты.
**Планируемое время работы:**
8 часов

**Comment by YerzhanUtelbayev** [comment]
Дополнил в соответствии с даннымим заказчика на текущий момент. Оставить ли поле выбора процедуры select элементом будет известно позже. Также на этой неделе поступят дополнительные данные по структуре данных. Я и @yelkanat решили оставить эти изменения на следующую итерацию.

**Comment by sv64ds** [comment]
Ознакомился с задачей, приступаю к решению, попробую за остаток сегодняшнего дня ознакомиться с текущей структурой формы, а если останется время, заменить селекты на инпуты
