### ISSUE TITLE
Форма планирования курса - submit handler

### ISSUE THREAD

**Issue by YerzhanUtelbayev** [Attractor-JS2/ESDP#46]
**Конечный результат:**
	Форма при подтверждении отправляет запрос на API со структурированным объектом.
**План решения:**
	Структурировать данные в объект с удобными для прочтения ключами.
	Добавить экшены для отправки запроса.
	Продумать визуальное подтверждение успешной отправки данных (уведомление и очистку полей формы или перенаправление).
**Мотивация:**
	Сохранение результата работы персонала для последующей обработки.
**Критерии приёмки:**
	Объект отправляемый при submit содержит все данные формы.
**Планируемое время работы:**
	2 часа.

**Comment by sv64ds** [comment]
Начал работу над тикетом, в первую очередь установлю зависимости axios, затем сделаю отдельный файл с экшнами, постараюсь сделать все максимально понятно и гибко
