### ISSUE TITLE
Эндпоинт сохранения плана лечения

### ISSUE THREAD

**Issue by YerzhanUtelbayev** [Attractor-JS2/ESDP#47]
**Конечный результат:**
	Роут и контроллер с методом сохранения данных плана лечения, для последующих операций.
**План решения:**
	Создать контроллер и подключить по роуту.
	Добавить метод сохранения данных в объекте глобального scope.
**Мотивация:**
Сохранение результата работы персонала для последующей обработки.
**Критерии приёмки:**
	Данные в POST запросе сохраняются и отправляется ответ успешного сохранения.
**Планируемое время работы:**
	3 часа.

**Comment by sv64ds** [comment]
Сажусь за работу, планирую контроллер реализовать через createRouter, в котором будут обработки get и post - запросов.
Сохранение и получение данных из объекта планирую сделать через fs

**Comment by sv64ds** [comment]
Закончил работу по тикету, пока не создаю pull-request, в той же ветке сажусь делать тикет #46
